name: scholar_nest
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  carousel_slider: ^5.1.1
  http: ^1.1.0
  google_fonts: ^5.0.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo.jpeg
    - assets/images/  # Folder for other images

  fonts:
    - family: Literata
      fonts:
        - asset: assets/fonts/static/Literata-Regular.ttf
        - asset: assets/fonts/static/Literata-Bold.ttf
          weight: 700
